spring:
  application:
    name:
      external-service
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto:
        none

server:
  port: ${SERVER_PORT:8080}

application.internal-service.host: ${INTERNAL_SERVER_HOST:localhost}
application.internal-service.port: ${INTERNAL_SERVER_PORT:8081}
