spring:
  application:
    name:
      external-service
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto:
        none
internal-service.host: ${INTERNAL_SERVER_HOST:localhost}
internal-service.port: ${INTERNAL_SERVER_PORT:8081}
server:
  port: ${SERVER_PORT:8080}
