apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-service
spec:
  selector:
    matchLabels:
      app: internal-service
  replicas: 1
  template:
    metadata:
      labels:
        app: internal-service
    spec:
      containers:
        - name: internal-service
          image: internal-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: internal-service
spec:
  selector:
    app: internal-service
  ports:
    - port: 8081
      targetPort: 8081
  clusterIP: None
