apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  internal-server.host: "internal-svc"
  internal-server.port: "8081"
  external-server.port: "8080"

  database.host: "database-sts-0.mysql-server-h.default.svc.cluster.local"
  database.port: "3306"
  database.user: "appuser"
  database.name: "kubernetes-poc"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  database.root.password: "cGFzc3dvcmQ="
  database.password: "dWx0cmEtc2VjdXJlLXBhc3N3b3JkLTEyMw=="
