apiVersion: v1
kind: Service
metadata:
  name: mysql-server-h
  labels:
    name: database-svc
    app: kubernetes-poc
spec:
  selector:
    name: database-po
  ports:
    - port: 3306
  clusterIP: None
