apiVersion: v1
kind: Pod
metadata:
  name: database-pod
  labels:
    name: database-pod
    app: kubernetes-poc
spec:
  containers:
    - name: mysql-server
      image: mysql/mysql-server:8.0.32-1.2.11-server
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
      volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        - name: database-persistent-storage
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-initdb
      configMap:
        name: mysql-initdb-config
    - name: database-persistent-storage
      persistentVolumeClaim:
        claimName: database-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS `kubernetes-poc`;
    CREATE USER 'development'@'%' IDENTIFIED BY 'password';
    GRANT ALL ON *.* TO 'development'@'%';
