apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-sts
  labels:
    name: database-deploy
    app: kubernetes-poc
spec:
  serviceName: mysql-server-h
  selector:
    matchLabels:
      name: database-po
      app: kubernetes-poc
  template:
    metadata:
      name: database-po
      labels:
        name: database-po
        app: kubernetes-poc
    spec:
      subdomain: mysql-server-h
      hostname: mysql-pod
      initContainers:
        - name: init-mysql-socket
          image: busybox
          command: [ 'sh', '-c', 'rm -f /var/lib/mysql/mysql.sock*' ]
          volumeMounts:
            - name: database-persistent-storage
              mountPath: /var/lib/mysql
      containers:
        - name: mysql-server
          image: mysql/mysql-server:8.0.32-1.2.11-server
          env:
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: database.user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: database.password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: database.name
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: database.root.password
            - name: MYSQL_ROOT_HOST
              value: "%"
          volumeMounts:
            - name: database-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: database-persistent-storage
          persistentVolumeClaim:
            claimName: database-pvc
