apiVersion: v1
kind: Service
metadata:
  name: external-service
  labels:
    name: external-service
    app: kubernetes-poc
spec:
  type: NodePort
  selector:
    name: external-service-pod
  ports:
    - port: 8080
      nodePort: 30000
