spring:
  application:
    name: internal-service
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/kubernetes-poc
    username: ${MYSQL_USER:development}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: ${SERVER_PORT:8081}
