apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  labels:
    name: database-pv
    app: kubernetes-poc
spec:
  storageClassName: standard
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
