apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  labels:
    name: database-pv
    app: kubernetes-poc
spec:
  storageClassName: do-block-storage
  csi:
    driver: dobs.csi.digitalocean.com
    volumeHandle: <volume-id>
